--
-- PXTPUBL  (Table) 
--
CREATE TABLE PXTPUBL
(
  PXTPUBL_ID         VARCHAR2(9 CHAR),
  PXTPUBL_PUBT_CODE  VARCHAR2(2 CHAR),
  PXTPUBL_TITLE      VARCHAR2(800 CHAR),
  PXTPUBL_PUBLISHER  VARCHAR2(60 CHAR),
  PXTPUBL_PUB_DATE   DATE,
  PXTPUBL_ISSUE      VARCHAR2(300 CHAR),
  PXTPUBL_VOLUME     VARCHAR2(25 CHAR),
  PXTPUBL_PAGES      VARCHAR2(25 CHAR)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY BAN_GUAUPLP_PZPMTIM_UPLOAD_DIR
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED BY NEWLINE CHARACTERSET US7ASCII skip 1 FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"' LDRTRIM MISSING FIELD VALUES ARE NULL REJECT ROWS
WITH ALL NULL FIELDS    )
     LOCATION (BAN_GUAUPLP_PZPMTIM_UPLOAD_DIR:'pxtpubl.csv')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
